/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: 4G.proto */

#ifndef PROTOBUF_C_4G_2eproto__INCLUDED
#define PROTOBUF_C_4G_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _LocationInfo LocationInfo;
typedef struct _NetInfo NetInfo;


/* --- enums --- */

typedef enum _NetInfo__NETTYPE {
  NET_INFO__NET__TYPE__NET_TYPE_NULL = 0,
  NET_INFO__NET__TYPE__NET_TYPE_2G = 1,
  NET_INFO__NET__TYPE__NET_TYPE_3G = 2,
  NET_INFO__NET__TYPE__NET_TYPE_4G = 3,
  NET_INFO__NET__TYPE__NET_TYPE_5G = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NET_INFO__NET__TYPE)
} NetInfo__NETTYPE;
typedef enum _NetInfo__SIGNALLEVEL {
  NET_INFO__SIGNAL__LEVEL__SIG_LEVEL0 = 0,
  NET_INFO__SIGNAL__LEVEL__SIG_LEVEL1 = 1,
  NET_INFO__SIGNAL__LEVEL__SIG_LEVEL2 = 2,
  NET_INFO__SIGNAL__LEVEL__SIG_LEVEL3 = 3,
  NET_INFO__SIGNAL__LEVEL__SIG_LEVEL4 = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NET_INFO__SIGNAL__LEVEL)
} NetInfo__SIGNALLEVEL;

/* --- messages --- */

/*
 * location information for gps
 */
struct  _LocationInfo
{
  ProtobufCMessage base;
  protobuf_c_boolean isvaild;
  int64_t timestamp;
  double latitude;
  double longitude;
  double altitude;
};
#define LOCATION_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&location_info__descriptor) \
    , 0, 0, 0, 0, 0 }


/*
 * location information for 4G net
 */
struct  _NetInfo
{
  ProtobufCMessage base;
  NetInfo__NETTYPE type;
  NetInfo__SIGNALLEVEL siglev;
  char *operator_;
};
#define NET_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&net_info__descriptor) \
    , NET_INFO__NET__TYPE__NET_TYPE_NULL, NET_INFO__SIGNAL__LEVEL__SIG_LEVEL0, NULL }


/* LocationInfo methods */
void   location_info__init
                     (LocationInfo         *message);
size_t location_info__get_packed_size
                     (const LocationInfo   *message);
size_t location_info__pack
                     (const LocationInfo   *message,
                      uint8_t             *out);
size_t location_info__pack_to_buffer
                     (const LocationInfo   *message,
                      ProtobufCBuffer     *buffer);
LocationInfo *
       location_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   location_info__free_unpacked
                     (LocationInfo *message,
                      ProtobufCAllocator *allocator);
/* NetInfo methods */
void   net_info__init
                     (NetInfo         *message);
size_t net_info__get_packed_size
                     (const NetInfo   *message);
size_t net_info__pack
                     (const NetInfo   *message,
                      uint8_t             *out);
size_t net_info__pack_to_buffer
                     (const NetInfo   *message,
                      ProtobufCBuffer     *buffer);
NetInfo *
       net_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   net_info__free_unpacked
                     (NetInfo *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*LocationInfo_Closure)
                 (const LocationInfo *message,
                  void *closure_data);
typedef void (*NetInfo_Closure)
                 (const NetInfo *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor location_info__descriptor;
extern const ProtobufCMessageDescriptor net_info__descriptor;
extern const ProtobufCEnumDescriptor    net_info__net__type__descriptor;
extern const ProtobufCEnumDescriptor    net_info__signal__level__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_4G_2eproto__INCLUDED */
