/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: 4G.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "4G.pb-c.h"
void   location_info__init
                     (LocationInfo         *message)
{
  static const LocationInfo init_value = LOCATION_INFO__INIT;
  *message = init_value;
}
size_t location_info__get_packed_size
                     (const LocationInfo *message)
{
  assert(message->base.descriptor == &location_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t location_info__pack
                     (const LocationInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &location_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t location_info__pack_to_buffer
                     (const LocationInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &location_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LocationInfo *
       location_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LocationInfo *)
     protobuf_c_message_unpack (&location_info__descriptor,
                                allocator, len, data);
}
void   location_info__free_unpacked
                     (LocationInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &location_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   net_info__init
                     (NetInfo         *message)
{
  static const NetInfo init_value = NET_INFO__INIT;
  *message = init_value;
}
size_t net_info__get_packed_size
                     (const NetInfo *message)
{
  assert(message->base.descriptor == &net_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t net_info__pack
                     (const NetInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &net_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t net_info__pack_to_buffer
                     (const NetInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &net_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NetInfo *
       net_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NetInfo *)
     protobuf_c_message_unpack (&net_info__descriptor,
                                allocator, len, data);
}
void   net_info__free_unpacked
                     (NetInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &net_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor location_info__field_descriptors[5] =
{
  {
    "isVaild",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(LocationInfo, isvaild),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(LocationInfo, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "latitude",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(LocationInfo, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(LocationInfo, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "altitude",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(LocationInfo, altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned location_info__field_indices_by_name[] = {
  4,   /* field[4] = altitude */
  0,   /* field[0] = isVaild */
  2,   /* field[2] = latitude */
  3,   /* field[3] = longitude */
  1,   /* field[1] = timestamp */
};
static const ProtobufCIntRange location_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor location_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LocationInfo",
  "LocationInfo",
  "LocationInfo",
  "",
  sizeof(LocationInfo),
  5,
  location_info__field_descriptors,
  location_info__field_indices_by_name,
  1,  location_info__number_ranges,
  (ProtobufCMessageInit) location_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue net_info__net__type__enum_values_by_number[5] =
{
  { "NET_TYPE_NULL", "NET_INFO__NET__TYPE__NET_TYPE_NULL", 0 },
  { "NET_TYPE_2G", "NET_INFO__NET__TYPE__NET_TYPE_2G", 1 },
  { "NET_TYPE_3G", "NET_INFO__NET__TYPE__NET_TYPE_3G", 2 },
  { "NET_TYPE_4G", "NET_INFO__NET__TYPE__NET_TYPE_4G", 3 },
  { "NET_TYPE_5G", "NET_INFO__NET__TYPE__NET_TYPE_5G", 4 },
};
static const ProtobufCIntRange net_info__net__type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex net_info__net__type__enum_values_by_name[5] =
{
  { "NET_TYPE_2G", 1 },
  { "NET_TYPE_3G", 2 },
  { "NET_TYPE_4G", 3 },
  { "NET_TYPE_5G", 4 },
  { "NET_TYPE_NULL", 0 },
};
const ProtobufCEnumDescriptor net_info__net__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "NetInfo.NET_TYPE",
  "NET_TYPE",
  "NetInfo__NETTYPE",
  "",
  5,
  net_info__net__type__enum_values_by_number,
  5,
  net_info__net__type__enum_values_by_name,
  1,
  net_info__net__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue net_info__signal__level__enum_values_by_number[5] =
{
  { "SIG_LEVEL0", "NET_INFO__SIGNAL__LEVEL__SIG_LEVEL0", 0 },
  { "SIG_LEVEL1", "NET_INFO__SIGNAL__LEVEL__SIG_LEVEL1", 1 },
  { "SIG_LEVEL2", "NET_INFO__SIGNAL__LEVEL__SIG_LEVEL2", 2 },
  { "SIG_LEVEL3", "NET_INFO__SIGNAL__LEVEL__SIG_LEVEL3", 3 },
  { "SIG_LEVEL4", "NET_INFO__SIGNAL__LEVEL__SIG_LEVEL4", 4 },
};
static const ProtobufCIntRange net_info__signal__level__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex net_info__signal__level__enum_values_by_name[5] =
{
  { "SIG_LEVEL0", 0 },
  { "SIG_LEVEL1", 1 },
  { "SIG_LEVEL2", 2 },
  { "SIG_LEVEL3", 3 },
  { "SIG_LEVEL4", 4 },
};
const ProtobufCEnumDescriptor net_info__signal__level__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "NetInfo.SIGNAL_LEVEL",
  "SIGNAL_LEVEL",
  "NetInfo__SIGNALLEVEL",
  "",
  5,
  net_info__signal__level__enum_values_by_number,
  5,
  net_info__signal__level__enum_values_by_name,
  1,
  net_info__signal__level__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor net_info__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(NetInfo, type),
    &net_info__net__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "siglev",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(NetInfo, siglev),
    &net_info__signal__level__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operator",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NetInfo, operator_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned net_info__field_indices_by_name[] = {
  2,   /* field[2] = operator */
  1,   /* field[1] = siglev */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange net_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor net_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NetInfo",
  "NetInfo",
  "NetInfo",
  "",
  sizeof(NetInfo),
  3,
  net_info__field_descriptors,
  net_info__field_indices_by_name,
  1,  net_info__number_ranges,
  (ProtobufCMessageInit) net_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
